obstacle_range: 6.5
raytrace_range: 8.5
footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
map_topic: /map
subscribe_to_updates: true
observation_sources: laser_scan_sensor 
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
global_frame: map
robot_base_frame: husky_robot_model__base_link
always_send_full_costmap: true

static_layer:
  map_topic: /map
  subscribe_to_updates: true

plugins:
  - {name: static,           type: "costmap_2d::StaticLayer"}
  - {name: obstacles,        type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,        type: "costmap_2d::InflationLayer"}
