footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
transform_tolerance: 5
update_frequency: 1
publish_frequency: 1
global_frame: map
robot_base_frame: husky_robot_model__base_link

plugins: 
    - {name: static,           type: "costmap_2d::StaticLayer"}
    - {name: explore_boundary, type: "frontier_exploration::BoundedExploreLayer"}
    - {name: inflation,        type: "costmap_2d::InflationLayer"}

static:
    map_topic: /map
    subscribe_to_updates: true
explore_boundary:
    resize_to_boundary: false
    frontier_travel_point: "middle" 
    explore_clear_space: false
inflation:
    inflation_radius: 0.5
