global_costmap:
  update_frequency: 0.5
  publish_frequency: 1.5
  transform_tolerance: 0.5
  width: 100
  height: 100
  origin_x: -7.5
  origin_y: -7.5
  static_map: false
  rolling_window: true
  inflation_radius: 1.2
  cost_scaling_factor: 1.3
  resolution: 0.02
  robot_radius: 0.6
